publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = ""
canonifyurls = true
theme = "hugo-academic-group"
title = "Population Health Studies Division - CHIRAL Bangladesh"
math = true
copyright = "&copy; Center for Health Innovation, Research, Action and Learning - Bangladesh"
enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "The PHSD team works on Bangladesh's public health issues. The design study for producing data for CHIRAL as well as preparing secondary data to give it a meaningful structure."
  author = "CHIRAL Bangladesh"
  email = "chiralbd@gmail.com"
  #youtube = "https://www.youtube.com/channel/UCAcwD0rF2Rm-sp1c2LUWh4w"
  address = '<a>Azimpur, 7/7, Dhaka, Bangladesh</a>'
  slogan = "CHIRAL<b>BD</b>"
  slogan_icon = "icon-spsbrats_logo"
  slogan_text = "The New Standard in Health Research"
  custom_css = ["biaslab.css"]
  landing_heading = "The New Standard in Health Research"
  landing_description = "The PHSD team works on Bangladesh's public health issues. The design study for producing data for CHIRAL as well as preparing secondary data to give it a meaningful structure."
  
  [[params.navbar_hierarchy]]
  name = "CHIRAL Bangladesh"
  link = "https://chiralbd.org/"
  position = 1
  #
  [[params.navbar_hierarchy]]
    name = "PHSD"
    link = "/"
    position = 2

  # [[params.sponsors]]
  #   name = "NWO"
  #   link = "http://www.stw.nl"
  #   image = "/img/sponsors/thals.png"
  #
  # [[params.sponsors]]
  #   name = "GN Resound"
  #   link = "http://www.resound.com/"
  #   image = "/img/sponsors/GNResound.png"



  # Selected Publications section.
  [params.publications_selected]
    detailed_list = false
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "News"
    subtitle = ""
    str_all = "More"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 6
    str_all = "More Projects"

  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.open_projects]
    title = "Open projects"
    subtitle = ""
    count = 3
    str_all = "All open projects"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.


  [[menu.main]]
    name = "Home"
    url = "/#home"
    weight = 2
 
[[menu.main]]
    name = "Projects"
    url = "/#projects"
    weight = 3

  [[menu.main]]
    name = "Team"
    url = "/#member"
    weight = 4


 [[menu.main]]
    name = "Teaching"
    identifier = "teaching"
    weight = 5

  [[menu.main]]
    name = "Ongoing: Python for Health Data Analytics(PY4HDA)"
    url = "/teaching/py4hda"
    parent = "teaching"
    weight = 1
    [[menu.main]]
    name = "All Training Modules"
    url = "/teaching/all_courses"
    parent = "teaching"
    weight = 2

 [[menu.main]]
    name = "Join"
    url = "/research/hdsc/"
    weight = 6
    
  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 7


 

  # [[menu.main]]
  #   name = "Software"
  #   weight = 3
  #   identifier = "software"

  # [[menu.main]]
  #   name = "ForneyLab.jl"
  #   url = "https://biaslab.github.io/ForneyLab.jl/stable/"
  #   parent = "software"
  #   weight = 1

  # [[menu.main]]
  #   name = "Rocket.jl"
  #   url = "https://biaslab.github.io/Rocket.jl/stable"
  #   parent = "software"
  #   weight = 2
